// import MessageCard from "@/components/MessageCard";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <>
      {/* <body */}
        {/* className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > */}
        <Navbar/>
        {/* <MessageCard /> */}
        {children}
        
      {/* </body> */}
      </>
        

  );
}
